export AWS_REGION="YOUR_AWS_REGION"
export AWS_ACCESS_KEY_ID="YOUR_AWS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="YOUR_AWS_ACCESS_KEY"
export GOOGLE_OAUTH_CLIENT_ID="YOUR_GOOGLE_CLIENT_ID"
export GOOGLE_OAUTH_CLIENT_SECRET="YOUR_GOOGLE_CLIENT_SECRET"
export GOOGLE_OAUTH_REDIRECT_URL="YOUR_GOOGLE_REDIRECT_URL"
export GIN_MODE=debug

echo "Variables are set."